development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
   url: 
   url: <%= ENV.fetch("REDIS_URL") { "redis://:uVgYuccelB9WRUK2abi7swSibXL3NNsl@redis-19099.c8.us-east-1-3.ec2.cloud.redislabs.com:19099" } %>
#  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: YallaNotlob_production
